name: Hotel App CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test Hotel App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: HotelApp

      - name: Check Expo project with expo-doctor
        run: npx expo-doctor
        working-directory: HotelApp

      - name: Prebuild project (Android)
        run: npx expo prebuild --no-install --platform android
        working-directory: HotelApp
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: HotelApp

      - name: Prebuild iOS project
        run: npx expo prebuild --no-install --platform ios
        working-directory: HotelApp
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
